
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    build:
      context: .
      dockerfile: service-discovery/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/service-discovery-ecommerce-boot:0.1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  cloud-config-container:
    build:
      context: .
      dockerfile: cloud-config/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/cloud-config-ecommerce-boot:0.1.0
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway-container:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/api-gateway-ecommerce-boot:0.1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'
  proxy-client-container:
    build:
      context: ./proxy-client
      dockerfile: Dockerfile
    image: selimhorri/proxy-client-ecommerce-boot:0.1.0
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'
  order-service-container:
    build:
      context: .
      dockerfile: order-service/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/order-service-ecommerce-boot:0.1.0
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'
  payment-service-container:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/payment-service-ecommerce-boot:0.1.0
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'
  product-service-container:
    build:
      context: .
      dockerfile: product-service/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/product-service-ecommerce-boot:0.1.0
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'
  shipping-service-container:
    build:
      context: .
      dockerfile: shipping-service/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/shipping-service-ecommerce-boot:0.1.0
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'
  user-service-container:
    build:
      context: .
      dockerfile: user-service/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/user-service-ecommerce-boot:0.1.0
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'
  favourite-service-container:
    build:
      context: .
      dockerfile: favourite-service/Dockerfile
      args:
        - PROJECT_VERSION=0.1.0
    image: selimhorri/favourite-service-ecommerce-boot:0.1.0
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - 'SPRING_APPLICATION_JSON={"eureka":{"client":{"service-url":{"defaultZone":"http://service-discovery-container:8761/eureka"}}}}'



