apiVersion: v1
kind: Service
metadata:
  name: proxy-client-service
spec:
  selector:
    app: proxy-client
  ports:
    - name: http
      port: 8900
      targetPort: 8900
      nodePort: 31000
  type: NodePort
