apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service
          image: us-central1-docker.pkg.dev/ecommerce-microservice-dev/ecommerce-repo/user-service:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8700
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config-service:9296
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://cloud-config-service:9296
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka":{"client":{"service-url":{"defaultZone":"http://eureka-service:8761/eureka"}}}}'
  #           # livenessProbe:
  #             httpGet:
  #               path: /actuator/health
  #               port: 8700
  #             initialDelaySeconds: 180
  #             periodSeconds: 10
  #             timeoutSeconds: 5
  #             failureThreshold: 10
  #           # readinessProbe:
  #             httpGet:
  #               path: /actuator/health
  #               port: 8700
  #             initialDelaySeconds: 120
  #             periodSeconds: 5
  #             timeoutSeconds: 3
  #             failureThreshold: 10
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
